name: CI Testing

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v16.14.0
        uses: actions/setup-node@v2
        with:
          node-version: 16.14.0
      - name: Install dependencies
        run: npm ci
      - run: npm run build --if-present
      - run: npm test
